### ISSUE TITLE
Make 2020 website

### ISSUE THREAD

**Issue by jchiatt** [jchiatt/magnoliajs.com#68]
For time's sake, probably just use same design/layout/etc as last year (this repo)

**Comment by tdfranklin** [comment]
Yea, I don't see any need to reinvent the wheel... keep the same site and just update w/ new info... if you want to throw the info my way, I'll be happy to update the site with this year's speakers, dates, etc.

**Comment by mtliendo** [comment]
I'd be nice for sharing if a refactor could be made to the speaker modal:

When clicking a speaker, the url should reflect the currently selected speaker. 

We could also standardize the card layout so that they didn't vary in size based on the content:

![image](https://user-images.githubusercontent.com/5106417/74590864-16118a80-4fd8-11ea-9987-8fec91e5be10.png)

**Comment by techieeliot** [comment]
I'm happy to help out here.
